version: '3.1'
services:
  stats-server:
    build:
      context: ./stats-service/server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
        - SPRING_PROFILES_ACTIVE=docker
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=stats
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

  #ewm-service:
  # ports:
  #  - "8080:8080"

  #ewm-db:
  #image: postgres:14-alpine
